# Site settings
title: RedPepper Documentation
description:
baseurl: "/docs"
url: "https://merlinz01.github.io/redpepper"
github_username: merlinz01

# Build settings
theme: jekyll-theme-dinky
plugins:
  - jekyll-remote-theme
