# Site settings
title: RedPepper Documentation
description: This is the documentation for the RedPepper project.
baseurl: "/docs"
url: "https://merlinz01.github.io/redpepper"
github_username: merlinz01

# Build settings
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
